# Generated by Django 5.2.4 on 2025-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '* '), (2, '* * '), (3, '* * * '), (4, '* * * * '), (5, '* * * * * '), (6, '* * * * * * '), (7, '* * * * * * * '), (8, '* * * * * * * * '), (9, '* * * * * * * * * '), (10, '* * * * * * * * * * ')], default=10),
        ),
    ]
